// packages/vue/src/components/collapse/index.vue
<script setup lang="ts">
import { provide, ref, toRefs, watch } from 'vue'
import type { IContext, IEmits, IProps, TName } from './types'
import { KEY } from './constants'

defineOptions({
  name: 'LarkCollapse',
})

const props = defineProps<IProps>()
const emits = defineEmits<IEmits>()

// const modelValue = toRef(props, 'modelValue');
const { modelValue, accordion } = toRefs(props)

const activeNames = ref<TName[]>([])

// watch(() => props.modelValue, () => {
watch(modelValue, () => {
  activeNames.value = modelValue.value
})

const setActiveNames = (names: TName[]) => {
  activeNames.value = names
  emits('update:modelValue', names)
  emits('change', names)
}

const handleClick = (name: TName) => {
  if (accordion.value) {
    setActiveNames(
      activeNames.value.length === 0 || activeNames.value[0] !== name ? [name] : []
    )
    return
  }

  if (activeNames.value.includes(name)) {
    setActiveNames(activeNames.value.filter((item) => item !== name))
  } else {
    setActiveNames([...activeNames.value, name])
  }
}

provide<IContext>(KEY, {
  activeNames,
  handleClick,
})
</script>

<template>
  <div class="lark-collapse">
    <slot></slot>
  </div>
</template>

// packages/react/src/components/collapse/index.tsx
import type { PropsWithClassName } from "@/types";
import type { IContext, IProps, TName } from "./types";
import { useEffect, useMemo, useState, type PropsWithChildren } from "react";
import classNames from "classnames";
import { Context } from "./constants";

function LarkCollapse(props: PropsWithClassName<PropsWithChildren<IProps>>) {
  const { className, accordion, onChange, children } = props;
  const [activeNames, setActiveNames] = useState<TName[]>(props.activeNames);

  useEffect(() => {
    setActiveNames(props.activeNames);
  }, [props]);

  const handleClick = (name: TName) => {
    let newActiveNames: TName[] = [];
    if (accordion) {
      newActiveNames =
        activeNames.length === 0 || activeNames[0] !== name ? [name] : [];
    } else {
      newActiveNames = activeNames.includes(name)
        ? activeNames.filter((item) => item !== name)
        : [...activeNames, name];
    }

    if (onChange) {
      onChange(newActiveNames);
    } else {
      setActiveNames(newActiveNames);
    }
  };

  const contextValue = useMemo<IContext>(() => {
    return {
      activeNames,
      handleClick,
    };
  }, [activeNames]);

  return (
    <Context.Provider value={contextValue}>
      <div className={classNames(className, "lark-collapse")}>{children}</div>
    </Context.Provider>
  );
}

export default LarkCollapse;
