// packages/react/src/components/message/index.tsx
import { useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react'
import type { IExpose, IProps } from './types'
import { getPrevBottomOffset } from './common'
import type { PropsWithClassName, PropsWithRef } from '@/types'
import { CSSTransition } from 'react-transition-group'
import classNames from 'classnames'
import LarkIcon from '@/components/icon'

function LarkMessage(props: PropsWithClassName<PropsWithRef<IProps, IExpose>>) {
  const {
    type = 'info',
    duration = 3000,
    offset = 20,
    id,
    zIndex,
    showClose,
    className,
    ref,
    message,
    onClose,
  } = props

  const nodeRef = useRef<HTMLDivElement | null>(null)
  const [alive, setAlive] = useState(true)
  const [height, setHeight] = useState(0)

  const topOffset = useMemo(() => {
    return getPrevBottomOffset(id) + offset
  }, [id, offset])

  const bottomOffset = useMemo(() => topOffset + height, [topOffset, height])

  useImperativeHandle<IExpose, IExpose>(
    ref,
    () => ({
      bottomOffset,
      alive,
    }),
    [],
  )

  const computedClass = useMemo(
    () => ({
      [`lark-message-${type}`]: type,
      'has-close': showClose,
    }),
    [type, showClose],
  )

  const computedStyle = useMemo(
    () => ({
      top: `${topOffset}px`,
      zIndex: zIndex,
    }),
    [topOffset, zIndex],
  )

  let timer: number | null | NodeJS.Timeout = null

  const startTimer = () => {
    // return
    if (duration === 0) {
      return
    }
    timer = setTimeout(() => {
      setAlive(false)
    }, duration)
  }

  const clearTimer = () => {
    if (timer) {
      clearTimeout(timer)
      timer = null
    }
  }

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Escape') {
      setAlive(false)
    }
  }

  document.addEventListener('keydown', handleKeyDown)

  useEffect(() => {
    startTimer()
    return () => {
      clearTimer()
      document.removeEventListener('keydown', handleKeyDown)
    }
  }, [])

  const handleEnter = () => {
    setHeight(nodeRef.current?.getBoundingClientRect().height ?? 0)
  }

  const handleExited = () => {
    onClose?.()
  }

  return (
    <CSSTransition
      nodeRef={nodeRef}
      classNames="fade-up"
      in={alive}
      unmountOnExit
      timeout={duration}
      onEnter={handleEnter}
      onExited={handleExited}
    >
      <div
        ref={nodeRef}
        className={classNames(className, 'lark-message', computedClass)}
        style={computedStyle}
      >
        <div className="lark-message__content">{message && <span>{message}</span>}</div>
        {showClose && (
          <div className="lark-message__close">
            <LarkIcon icon="xmark" />
          </div>
        )}
      </div>
    </CSSTransition>
  )
}

export default LarkMessage

// packages/vue/src/components/message/index.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, toRefs, useTemplateRef } from 'vue'
import type { IExpose, IProps } from './types'
import { getPrevBottomOffset } from './main'
import LarkComponent from '@/components/common'
import LarkIcon from '@/components/icon/index.vue'

const props = withDefaults(defineProps<IProps>(), {
  type: 'info',
  duration: 3000,
  offset: 20,
})

defineOptions({
  name: 'LarkMessage',
})

const { id, offset, zIndex, duration, type, showClose } = toRefs(props)
const nodeRef = useTemplateRef('message-ref')
const alive = ref(true)
const height = ref(0)

const topOffset = computed(() => {
  return getPrevBottomOffset(id.value) + offset.value
})

const bottomOffset = computed(() => {
  return topOffset.value + height.value
})

defineExpose<IExpose>({
  bottomOffset: bottomOffset.value,
  alive,
})

const computedClass = computed(() => ({
  [`lark-message--${type.value}`]: type.value,
  'has-close': showClose.value,
}))

const computedStyle = computed(() => ({
  top: `${topOffset.value}px`,
  zIndex: zIndex.value,
}))

let timer: number | null = null

const startTimer = () => {
  // return
  if (duration.value === 0) {
    return
  }
  timer = setTimeout(() => {
    alive.value = false
  }, duration.value)
}

const clearTimer = () => {
  if (timer) {
    clearTimeout(timer)
    timer = null
  }
}

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Escape') {
    alive.value = false
  }
}

document.addEventListener('keydown', handleKeyDown)

onMounted(() => {
  alive.value = true
  startTimer()
})

onUnmounted(() => {
  clearTimer()
  document.removeEventListener('keydown', handleKeyDown)
})

const handleEnter = () => {
  height.value = nodeRef.value?.getBoundingClientRect().height ?? 0
}

const handleAfterLeave = () => {
  props.onClose?.()
}
</script>

<template>
  <Transition
    name="fade-up"
    @after-leave="handleAfterLeave"
    @enter="handleEnter"
    :duration="duration"
  >
    <div
      class="lark-message"
      v-if="alive"
      :class="computedClass"
      ref="message-ref"
      :style="computedStyle"
      @mouseenter="clearTimer"
      @mouseleave="startTimer"
    >
      <div class="lark-message__content">
        <LarkComponent v-if="message" :element="message" />
      </div>

      <div class="lark-message__close" v-if="showClose">
        <LarkIcon @click.stop="alive = false" icon="xmark" />
      </div>
    </div>
  </Transition>
</template>
