// packages/vue/src/pages/message/index.vue
<script lang="ts" setup>
import LarkButton from '@/components/button/index.vue'
import LarkToast from '@/components/message/toast'
</script>

<template>
  <LarkButton type="success" @click="LarkToast.success('Success')">Success</LarkButton>
  <LarkButton type="error" @click="LarkToast.success('Error')">Error</LarkButton>
  <LarkButton type="warning" @click="LarkToast.success('Warning')">Warning</LarkButton>
  <LarkButton type="info" @click="LarkToast.success('Info')">Info</LarkButton>
</template>

// packages/react/src/pages/message/index.tsx
import LarkButton from '@/components/button'
import LarkToast from '@/components/message/toast'

function Index() {
  return (
    <>
      <LarkButton type="success" onClick={() => LarkToast.success('Success')}>
        Success
      </LarkButton>
      <LarkButton type="error" onClick={() => LarkToast.error('Error')}>
        Error
      </LarkButton>
      <LarkButton type="warning" onClick={() => LarkToast.warning('Warning')}>
        Warning
      </LarkButton>
      <LarkButton type="info" onClick={() => LarkToast.info('Info')}>
        Info
      </LarkButton>
      <LarkButton type="success" plain onClick={() => LarkToast.closeAll()}>
        Close All
      </LarkButton>
    </>
  )
}

export default Index
